#./config/routes.yaml
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path:       /token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
